
var ApiGen = ApiGen || {};
ApiGen.elements = [["c","GlpiPlugin\\Flyvemdm\\Exception\\AgentSendQueryException"],
["c","GlpiPlugin\\Flyvemdm\\Exception\\FusionInventoryRuleInconsistency"],
["c","GlpiPlugin\\Flyvemdm\\Exception\\PolicyApplicationException"],
["c","GlpiPlugin\\Flyvemdm\\Exception\\TaskPublishPolicyBadFleetException"],
["c","GlpiPlugin\\Flyvemdm\\Exception\\TaskPublishPolicyPolicyNotFoundException"],
["c","PluginFlyvemdmAgent"],
["c","PluginFlyvemdmCommon"],
["c","PluginFlyvemdmConfig"],["c","PluginFlyvemdmDeployable"],
["c","PluginFlyvemdmEntityConfig"],["c","PluginFlyvemdmFile"],
["c","PluginFlyvemdmFleet"],["c","PluginFlyvemdmFusionInventory"],["c","PluginFlyvemdmGeolocation"],
["c","PluginFlyvemdmGraph"],["c","PluginFlyvemdmInvitation"],["c","PluginFlyvemdmInvitationlog"],
["c","PluginFlyvemdmMenu"],["c","PluginFlyvemdmMqttacl"],["c","PluginFlyvemdmMqttclient"],
["c","PluginFlyvemdmMqtthandler"],["c","PluginFlyvemdmMqttlog"],["c","PluginFlyvemdmMqttuser"],
["c","PluginFlyvemdmNotifiableInterface"],["c","PluginFlyvemdmNotificationTargetInvitation"],
["c","PluginFlyvemdmPackage"],["c","PluginFlyvemdmPolicy"],["c","PluginFlyvemdmPolicyBase"],
["c","PluginFlyvemdmPolicyBoolean"],["c","PluginFlyvemdmPolicyCategory"],
["c","PluginFlyvemdmPolicyDeployapplication"],["c","PluginFlyvemdmPolicyDeployfile"],
["c","PluginFlyvemdmPolicyDropdown"],["c","PluginFlyvemdmPolicyFactory"],
["c","PluginFlyvemdmPolicyInteger"],["c","PluginFlyvemdmPolicyInterface"],
["c","PluginFlyvemdmPolicyRemoveapplication"],["c","PluginFlyvemdmPolicyRemovefile"],
["c","PluginFlyvemdmPolicyString"],["c","PluginFlyvemdmProfile"],["c","PluginFlyvemdmTask"],
["c","PluginFlyvemdmTaskstatus"],["c","PluginFlyvemdmUpkparser"],["c","PluginFlyvemdmWellknownpath"]];
